path = "/etc/rspamd/keys/$domain.$selector.key";
selector = "mail";
enabled = true;
sign_local = true;
auth_only = false;
try_fallback = true;
allow_hdrfrom_mismatch = false;
allow_username_mismatch = true;